---
- name: Create log directory and file on Windows host
  hosts: win_nodes
  gather_facts: false

  vars:
    log_dir: 'C:\\tmp\\log'
    log_file: 'C:\\tmp\\log\\lofile.log'
    log_content: |
      #####################################################
      #               Windows Node Log File               #
      #####################################################
      Hostname: {{ inventory_hostname }}
      Timestamp: {{ ansible_date_time.iso8601 }}
      Message: Log file created via Ansible AWX.
      #####################################################

  tasks:
    - name: Ensure log directory exists on Windows
      ansible.windows.win_file:
        path: "{{ log_dir }}"
        state: directory

    - name: Write log content to file
      ansible.windows.win_copy:
        content: "{{ log_content }}"
        dest: "{{ log_file }}"
        force: true  # Overwrites each time. Use 'false' to prevent overwriting
