---
- name: Health Check for Linux and Windows Nodes
  hosts: all
  gather_facts: true

  tasks:
    - name: Set OS family fact
      set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"

    # --- Linux execution ---
    - name: Run check.sh on Linux
      when: os_family == "RedHat"
      script: ../scripts/check.sh
      register: linux_script_out
      changed_when: false

    # --- Windows execution ---
    - name: Run check.ps1 on Windows
      when: os_family == "Windows"
      block:
        - name: Ensure C:\Temp exists
          win_file:
            path: C:\Temp
            state: directory

        - name: Copy check.ps1 to Windows node
          win_copy:
            src: ../scripts/check.ps1
            dest: C:\Temp\check.ps1

        - name: Execute PowerShell script
          win_shell: C:\Temp\check.ps1
          register: win_script_out
          changed_when: false

    # --- Extract and set metrics ---
    - name: Parse script output and determine health status
      set_fact:
        cpu: "{{ cpu_val }}"
        ram: "{{ ram_val }}"
        disk: "{{ disk_val }}"
        status: "{{ 'CRITICAL' if cpu_val | float > 60 or ram_val | float > 60 or disk_val | float > 60 else 'GOOD' }}"
      vars:
        script_output: "{{ linux_script_out.stdout if os_family == 'RedHat' else win_script_out.stdout }}"
        cpu_val: "{{ script_output | regex_search('CPU=(\\d+\\.?\\d*)', '\\1') | first | default('0') }}"
        ram_val: "{{ script_output | regex_search('RAM=(\\d+\\.?\\d*)', '\\1') | first | default('0') }}"
        disk_val: "{{ script_output | regex_search('DISK=(\\d+\\.?\\d*)', '\\1') | first | default('0') }}"

# ----------------------------------------------------------------------
- name: Save Health Summary on Control Node (/tmp)
  hosts: localhost
  gather_facts: true
  vars:
    log_dir: /tmp/health_logs
    log_filename: "health_check_{{ ansible_date_time.date }}_{{ ansible_date_time.time | regex_replace(':', '') }}.log"

  tasks:
    - name: Ensure log directory exists
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'

    - name: Build summary content
      set_fact:
        summary_output: |
          ####################################################################
          #                    Node Health Check Report                      #
          ####################################################################
          {% for host in hostvars if hostvars[host].cpu is defined %}
          HOST:   {{ hostvars[host].inventory_hostname }}
          OS:     {{ hostvars[host].os_family | default('N/A') }}
          CPU:    {{ hostvars[host].cpu | float | round(2) }}%
          RAM:    {{ hostvars[host].ram | float | round(2) }}%
          DISK:   {{ hostvars[host].disk | float | round(2) }}%
          STATUS: {{ hostvars[host].status | default('FAILED') }}
          --------------------------------------------------------------------
          {% endfor %}
          Time: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          Executed by: {{ ansible_user_id }}
          ####################################################################

    - name: Write health summary to log file
      copy:
        content: "{{ summary_output }}"
        dest: "{{ log_dir }}/{{ log_filename }}"

    - name: Display summary in AWX job output
      debug:
        msg: "{{ summary_output }}"
